[build-system]
requires = ["uv_build>=0.9.3,<0.10.0"]
build-backend = "uv_build"

[project]
name = "ingress"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = ["utils"]

[tool.uv.build-backend]
module-name = "ingress"
module-root = ""
