apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: postgresql-system-trixie
  labels:
    images.cnpg.io/family: postgresql
    images.cnpg.io/type: system
    images.cnpg.io/os: trixie
    images.cnpg.io/date: '20260220'
    images.cnpg.io/publisher: cnpg.io
spec:
  images:
  - major: 13
    image: ghcr.io/cloudnative-pg/postgresql:13.22-202511100817-system-trixie@sha256:c3cb9c42e2940c5205218f1d527cbbdb894611eed028b1c8ee61123b820bff73
  - major: 14
    image: ghcr.io/cloudnative-pg/postgresql:14.21-202602201511-system-trixie@sha256:6e2805d11a21a4ef7d7e37fdf89850b4fc62250529778966fc89f00ae7ca5f16
  - major: 15
    image: ghcr.io/cloudnative-pg/postgresql:15.16-202602201511-system-trixie@sha256:6b3296ece78f285d93c18b7d33c151cf9c447f9f768b227092877b606510c820
  - major: 16
    image: ghcr.io/cloudnative-pg/postgresql:16.12-202602201511-system-trixie@sha256:180752390a5dc6cacf7773f8c4bdf4b3d667fc738ee1bf10ce521f829fca4de6
  - major: 17
    image: ghcr.io/cloudnative-pg/postgresql:17.8-202602201511-system-trixie@sha256:9156a5d88a6393101a7f1c63bca2ecda685b263f13dc5b8de165d0164ddac82b
  - major: 18
    image: ghcr.io/cloudnative-pg/postgresql:18.2-202602201511-system-trixie@sha256:f92ca5c5d00f56203a0067e11a36c6f27bb42e94bff09477caa695e7429e8dc3
