apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: postgresql-standard-trixie
  labels:
    images.cnpg.io/family: postgresql
    images.cnpg.io/type: standard
    images.cnpg.io/os: trixie
    images.cnpg.io/date: '20260220'
    images.cnpg.io/publisher: cnpg.io
spec:
  images:
  - major: 13
    image: ghcr.io/cloudnative-pg/postgresql:13.22-202511100817-standard-trixie@sha256:8252529362b12a451a18cb19fdec9174ea09709102a7e6cf2e2b24d140dbd181
  - major: 14
    image: ghcr.io/cloudnative-pg/postgresql:14.21-202602201511-standard-trixie@sha256:516604302ce281911fc1fa570a7efb7c50658a937d2bda4dd0a46974d75e7127
  - major: 15
    image: ghcr.io/cloudnative-pg/postgresql:15.16-202602201511-standard-trixie@sha256:9b6786e00fe30a15e30e2345e4e93a745aed06c055a82b0a77d7cedd5732a1b5
  - major: 16
    image: ghcr.io/cloudnative-pg/postgresql:16.12-202602201511-standard-trixie@sha256:8f5f69d117305bd732e971f62fe2a82ff64afe45e4e84e125237301a6d32de6c
  - major: 17
    image: ghcr.io/cloudnative-pg/postgresql:17.8-202602201511-standard-trixie@sha256:07945f25eb8425e6b923aaf6019318e989ddce3775aa42b43a199c621be57015
  - major: 18
    image: ghcr.io/cloudnative-pg/postgresql:18.2-202602201511-standard-trixie@sha256:c138ec706d9fc5890f4a58dbda2ea2b8eb98822eeb9a67293b67dc7261b14e70
