apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: postgresql-minimal-bookworm
  labels:
    images.cnpg.io/family: postgresql
    images.cnpg.io/type: minimal
    images.cnpg.io/os: bookworm
    images.cnpg.io/date: '20260220'
    images.cnpg.io/publisher: cnpg.io
spec:
  images:
  - major: 13
    image: ghcr.io/cloudnative-pg/postgresql:13.22-202511100817-minimal-bookworm@sha256:02e8ffc71aec2768ca177711278d3c0e6ceb5403df5fa6d3780cd590332e3a5d
  - major: 14
    image: ghcr.io/cloudnative-pg/postgresql:14.21-202602201511-minimal-bookworm@sha256:ca47952e56d26cac99e9fda1737dcaa9483b8d9180992bf76765a9f451289bbf
  - major: 15
    image: ghcr.io/cloudnative-pg/postgresql:15.16-202602201511-minimal-bookworm@sha256:972cf41dc4fcc5b0a4cc5bf3c6007fa10b5749e7333530b0d6b25e3c68285c3b
  - major: 16
    image: ghcr.io/cloudnative-pg/postgresql:16.12-202602201511-minimal-bookworm@sha256:7ab323c028680f551e2dab45b1854edac7dd4d8f9a308fd08588096a535bbbdc
  - major: 17
    image: ghcr.io/cloudnative-pg/postgresql:17.8-202602201511-minimal-bookworm@sha256:3e05e47d243f39c6bd01fdfc38f5a624a75efbdf487d95303552daadce01e8c0
  - major: 18
    image: ghcr.io/cloudnative-pg/postgresql:18.2-202602201511-minimal-bookworm@sha256:9e437993bacd60edebacd795107fbac59fee9db8a76250fe499432f5c48ab6f3
