apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: postgresql-minimal-bullseye
  labels:
    images.cnpg.io/family: postgresql
    images.cnpg.io/type: minimal
    images.cnpg.io/os: bullseye
    images.cnpg.io/date: '20260220'
    images.cnpg.io/publisher: cnpg.io
spec:
  images:
  - major: 13
    image: ghcr.io/cloudnative-pg/postgresql:13.22-202511100817-minimal-bullseye@sha256:e8f3dd320ec555ee810ca62e04538880ca77855901762629eac441da173b5639
  - major: 14
    image: ghcr.io/cloudnative-pg/postgresql:14.21-202602201511-minimal-bullseye@sha256:31a91b58118247df6636a2ea7feeb92f4e43ac6253aacc6075e15a4505416338
  - major: 15
    image: ghcr.io/cloudnative-pg/postgresql:15.16-202602201511-minimal-bullseye@sha256:cc225c66ce8604b5d3e5305e6661777899e30da325db1771e3ad07293b624a3e
  - major: 16
    image: ghcr.io/cloudnative-pg/postgresql:16.12-202602201511-minimal-bullseye@sha256:15bd84c111b21d5c289bf5de7bd40886306c9298d3924e738be44289643931de
  - major: 17
    image: ghcr.io/cloudnative-pg/postgresql:17.8-202602201511-minimal-bullseye@sha256:20fe5f2ca43d1668c1c08d37862a4d1356c6b7012c39ce2ac645c80bad300bd1
  - major: 18
    image: ghcr.io/cloudnative-pg/postgresql:18.2-202602201511-minimal-bullseye@sha256:5d1451b7ae8571d7951bf7917fade0d12ba33ba296600526e75a5f3fd2ef7049
