[build-system]
requires = ["uv_build>=0.10.0,<0.11.0"]
build-backend = "uv_build"

[project]
name = "s3"
version = "0.1.0"
requires-python = ">=3.11"

dependencies = ["utils"]

[tool.uv.build-backend]
module-name = "s3"
module-root = ""
