[build-system]
requires = ["uv_build>=0.10.0,<0.11.0"]
build-backend = "uv_build"

[project]
name = "paperless"
version = "0.1.0"
requires-python = ">=3.11"

dependencies = ["pulumi-postgresql>=3.15.0", "utils"]

[tool.uv.build-backend]
module-name = "paperless"
module-root = ""
