[project]
name = "netbox"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = ["utils"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.build-backend]
module-name = "netbox"
module-root = ""
